### ISSUE TITLE
Audio Wizard is not working

### ISSUE THREAD

**Issue by sobuj53** [reiryuki/Audio-Wizard-DTS-Headphone-X-Asus-Zenfone-5#1]
Hi,

I've installed DTS on my Xaiomi Mi5 (Crdroid A11), rebooted 2 times after installation but the audio wizard is showing blank screen

![photo_2021-01-20_00-59-16](https://user-images.githubusercontent.com/25761237/105080527-202aeb80-5abb-11eb-86c7-9a1a4bde6f60.jpg)

Here are the magisk installation log and Matlog 
[magisk_install_log.log](https://github.com/reiryuki/Audio-Wizard-DTS-Headphone-X-Asus-Zenfone-5/files/5838050/magisk_install_log.log)
[DTS_Log.txt](https://github.com/reiryuki/Audio-Wizard-DTS-Headphone-X-Asus-Zenfone-5/files/5838052/DTS_Log.txt)

I'd really appreciate if you could take a look at this.

**Comment by reiryuki** [comment]
Use permissive method
See troubleshoots
