### ISSUE TITLE
About compress offload playback, thanks 

### ISSUE THREAD

**Issue by shandongtlb** [reiryuki/Audio-Wizard-DTS-Headphone-X-Asus-Zenfone-5#3]
Hello, I am a fan of you, and it feels very good and incredible after I flashed in the dts headphone X module you made. But now I have encountered a bug, some apps have no sound. As you said, it should not be compatible with compress offload playback. So is there any way to solve this problem? I feel very important. In addition, I am also learning the Android audio framework recently. If I can, maybe I can help to ease your hard work. In short, thank you very much for your module, best wishes!

Also, do you still need logs ? If you need, I will upload it.

**Comment by reiryuki** [comment]
logcats required

**Comment by shandongtlb** [comment]
I turned on the Audio Wizard app, the "Play Music Preview" button in the upper right corner, no sound; then, I turned on QQ app again, the built-in song listening function, no sound.
[log1.txt](https://github.com/reiryuki/Audio-Wizard-DTS-Headphone-X-Asus-Zenfone-5/files/5872417/log1.txt)


logcat close

**Comment by shandongtlb** [comment]
I am using device is Xiaomi Mi9, sm8150 soc, thanks

**Comment by reiryuki** [comment]
Tried a common music player like youtube music?
Chinese music players usually forcing playback to use compress offload even its deactivated by module

Also send your audio_policy_configuration.xml file

**Comment by shandongtlb** [comment]
I tried it, YouTube and some other players can play normally, and the effect is very good
[audio_policy_configuration.xml.txt](https://github.com/reiryuki/Audio-Wizard-DTS-Headphone-X-Asus-Zenfone-5/files/5872676/audio_policy_configuration.xml.txt)

**Comment by reiryuki** [comment]
Ok then that is the music player problem which only support compress offload, doesn't support deep buffer nor low latency. No wrong with Audio Wizard.

If you wanna join my audio port developer tg group, pm me tg @reiryuki

**Comment by shandongtlb** [comment]
Okay, and can you add support, or force the sound to compress offload?

**Comment by reiryuki** [comment]
No
